<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.0 on win32)" generated="20210302 17:42:42.509" rpa="false">
<suite id="s1" name="Test Selenium" source="C:\Users\aldo-\OneDrive\job\RobotFramework\test_selenium.robot">
<test id="s1-t1" name="TC1:dgdg">
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>https://playtictactoe.org/</arg>
<arg>chrome</arg>
</arguments>
<msg timestamp="20210302 17:42:42.848" level="INFO">Opening browser 'chrome' to base url 'https://playtictactoe.org/'.</msg>
<status status="PASS" starttime="20210302 17:42:42.848" endtime="20210302 17:42:45.620"></status>
</kw>
<kw name="Get Element Attribute" library="SeleniumLibrary">
<doc>Returns the value of ``attribute`` from the element ``locator``.</doc>
<arguments>
<arg>xpath://html/body/div[4]/p[1]/span[4]</arg>
<arg>innerHTML</arg>
</arguments>
<assign>
<var>${var}</var>
</assign>
<msg timestamp="20210302 17:42:45.655" level="INFO">${var} = 0</msg>
<status status="PASS" starttime="20210302 17:42:45.621" endtime="20210302 17:42:45.655"></status>
</kw>
<kw name="Log To Console" library="BuiltIn">
<doc>Logs the given message to the console.</doc>
<arguments>
<arg>${var}</arg>
</arguments>
<status status="PASS" starttime="20210302 17:42:45.656" endtime="20210302 17:42:45.657"></status>
</kw>
<status status="PASS" starttime="20210302 17:42:42.847" endtime="20210302 17:42:45.657" critical="yes"></status>
</test>
<status status="PASS" starttime="20210302 17:42:42.513" endtime="20210302 17:42:45.660"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" id="s1" name="Test Selenium">Test Selenium</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210302 17:42:42.845" level="ERROR">Error in file 'C:\Users\aldo-\OneDrive\job\RobotFramework\test_selenium.robot' on line 3: Importing test library 'Selenium.webdriver.common.by' failed: ModuleNotFoundError: No module named 'Selenium'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\aldo-\AppData\Local\Programs\Python\Python39-32\Scripts\robot.exe
  c:\users\aldo-\appdata\local\programs\python\python39-32\python39.zip
  c:\users\aldo-\appdata\local\programs\python\python39-32\DLLs
  c:\users\aldo-\appdata\local\programs\python\python39-32\lib
  c:\users\aldo-\appdata\local\programs\python\python39-32
  C:\Users\aldo-\AppData\Roaming\Python\Python39\site-packages
  c:\users\aldo-\appdata\local\programs\python\python39-32\lib\site-packages
  c:\users\aldo-\appdata\local\programs\python\python39-32\lib\site-packages\win32
  c:\users\aldo-\appdata\local\programs\python\python39-32\lib\site-packages\win32\lib
  c:\users\aldo-\appdata\local\programs\python\python39-32\lib\site-packages\Pythonwin</msg>
</errors>
</robot>
